name: simple_dart_modal_controller
description: Modal Controller
version: 0.0.1
repository: https://github.com/simple-dart/modal_controller
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.2

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers:
