name: simple_dart_modal_controller
description: Modal Controller
version: 0.0.7
repository: https://github.com/simple-dart/modal_controller
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.3
